/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cordova.plugin.dinpay;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int action_settings=0x7f080013;
        public static final int btn_submit1=0x7f080010;
        public static final int btn_submit2=0x7f080011;
        public static final int edt_customer_idNumber=0x7f08000e;
        public static final int edt_customer_name=0x7f08000d;
        public static final int edt_extra_return_param=0x7f08000c;
        public static final int edt_httpurl=0x7f08000f;
        public static final int edt_merchantcode=0x7f080000;
        public static final int edt_notifyurl=0x7f080001;
        public static final int edt_orderamount=0x7f080006;
        public static final int edt_orderno=0x7f080004;
        public static final int edt_ordertime=0x7f080005;
        public static final int edt_productcode=0x7f080009;
        public static final int edt_productname=0x7f080007;
        public static final int edt_productnum=0x7f08000a;
        public static final int edt_produnctdesc=0x7f08000b;
        public static final int edt_redoflag=0x7f080008;
        public static final int edt_signtype=0x7f080003;
        public static final int edt_version=0x7f080002;
        public static final int merchant_payResult=0x7f080012;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int merchant_pay_result=0x7f030001;
    }
    public static final class menu {
        public static final int main=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050002;
        public static final int app_name=0x7f050000;
        public static final int comment=0x7f050004;
        public static final int hello_world=0x7f050001;
        public static final int title_activity_merchant_pay_result=0x7f050003;
    }
    public static final class style {
        /** 
        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060001;
        /**  银联控件样式 
         */
        public static final int Theme_UPPay=0x7f060000;
    }
}
